<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Select the file with IDs users to import. File size should not exceed 1MB.' => 'Оберіть файл з ідентифікаторами користувачів для імпорту. Розмір файлу не повинен перевищувати 1MB.',
    'Add user' => 'Додати запис',
    'Are you sure you want to delete this item?' => 'Ви впевнені, що хочете видалити цей запис?',
    'Bib Ref' => 'Бібліографічні посилання',
    'Center library electronic resources and technologies' => 'Центр бібліотечних електронних ресурсів і технологій',
    'Citation' => 'Цитування',
    'Citations' => 'Цитування',
    'Close' => 'Закрити',
    'Create' => 'Створити',
    'Create Citation' => 'Створити запис',
    'Delete' => 'Видалити',
    'Department of Information and Communication Technologies' => 'Відділ інформаційно-комунікаційних технологій',
    'Export data' => 'Експорт даних',
    'Fetch data' => 'Отримати дані',
    'File with user IDs' => 'Файл з ідентифікаторами користувачів',
    'Google Scholar Parser' => 'Google Scholar Аналізатор',
    'H Index' => 'h-індекс',
    'Head of the Centre, Candidate of Technical Sciences, Ph.D. of Social Communications' => 'керівник Центру, кандидат технічних наук, доктор наук із соціальних комунікацій',
    'ID' => 'ID',
    'Import users from file' => 'Імпорт користувачів з файлу',
    'Incorrect username or password.' => 'Неправильне логін користувача або пароль.',
    'LOBUZІNA Katerina Vіlentіїvna' => 'ЛОБУЗІНА Катерина Вілентіївна',
    'Loading' => 'Завантаження',
    'Login' => 'Увійти',
    'Logout ({0})' => 'Вийти ({0})',
    'Missing' => 'Відсутній',
    'Password' => 'Пароль',
    'Please fill out the following fields to login' => 'Будь ласка, заповніть наступні поля для входу',
    'Present' => 'В наявності',
    'Remember Me' => 'Запам\'ятати мене',
    'The results of the import' => 'Результати імпорту',
    'This ID does not look like the right one for Google Scholar' => 'Цей ідентифікатор не виглядає як правильний для Google Scholar',
    'Update' => 'Змінити',
    'Update At' => 'Змінено',
    'Update {modelClass}: ' => 'Змінити',
    'Upload' => 'Завантажити',
    'User ID' => 'Ідентифікатор користувача',
    'Username' => 'Логін користувача',
    'Vernadsky National Library of Ukraine' => 'Національна бібліотека України імені В. І. Вернадського',
    '{user} - {status}' => '{user} - {status}',
];
