<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add user' => '',
    'Are you sure you want to delete this item?' => '',
    'Bib Ref' => '',
    'Citation' => '',
    'Citations' => '',
    'Create' => '',
    'Create Citation' => '',
    'Delete' => '',
    'Export data' => '',
    'Google Scholar Parser' => '',
    'H Index' => '',
    'ID' => '',
    'Incorrect username or password.' => '',
    'Login' => '',
    'Logout ({0})' => '',
    'Missing' => '',
    'Password' => '',
    'Please fill out the following fields to login' => '',
    'Present' => '',
    'Remember Me' => '',
    'Update' => '',
    'Update At' => '',
    'Update {modelClass}: ' => '',
    'User ID' => '',
    'Username' => '',
    'Vernadsky National Library of Ukraine' => '',
];
